# SELECT * FROM mimic3_demo.PATIENTS

# SELECT SUBJECT_ID, GENDER FROM mimic3_demo.PATIENTS

# SELECT SUBJECT_ID, GENDER FROM mimic3_demo.PATIENTS WHERE GENDER="F"

# SELECT distinct gender FROM `mimic3_demo.PATIENTS`

# SELECT ADMISSION_LOCATION FROM `mimic3_demo.ADMISSIONS`
#  GROUP BY ADMISSION_LOCATION

# SELECT LONG_TITLE FROM `mimic3_demo.D_ICD_DIAGNOSES`
#   GROUP BY LONG_TITLE

#SELECT LONG_TITLE FROM `mimic3_demo.D_ICD_DIAGNOSES`
#  WHERE lower(LONG_TITLE) like "%diabetes%"
#  GROUP BY LONG_TITLE

#SELECT count(*) FROM `mimic3_demo.ADMISSIONS`

#SELECT count(HADM_ID) FROM `mimic3_demo.ADMISSIONS`

#SELECT count(HADM_ID), min(ADMITTIME) FROM `mimic3_demo.ADMISSIONS`

#SELECT count(HADM_ID) as NUMBER_OF_ADMISSIONS, min(ADMITTIME) as EARLIEST_ADMISSION FROM `mimic3_demo.ADMISSIONS`

# SELECT count(HADM_ID) FROM `mimic3_demo.ADMISSIONS` WHERE ADMISSION_LOCATION = 'EMERGENCY ROOM ADMIT'

#SELECT count(distinct SUBJECT_ID) FROM `mimic3_demo.ADMISSIONS`

SELECT SUBJECT_ID, count(distinct HADM_ID) as ADMISSION_COUNT FROM `mimic3_demo.ADMISSIONS` GROUP BY SUBJECT_ID ORDER BY ADMISSION_COUNT desc










